/* 
 * Earth Computing Network Link Device User API
 * Copyright(c) 2016 Earth Computing.
 *
 *  Author: Atsushi Kasuya
 *
 */

#ifndef _ECNL_USER_API_H_
#define _ECNL_USER_API_H_

#define ECND_GENL_NAME "ECND_Family"

#define NL_ECND_MULTICAST_GOUP_LINKSTATUS		"status"
#define NL_ECND_MULTICAST_GOUP_AIT				"ait"
#define NL_ECND_MULTICAST_GOUP_TEST				"test"

/* attributes */
enum nl_ecnd_attributes {
	NL_ECND_ATTR_UNSPEC,

	NL_ECND_ATTR_DEVICE_NAME,
	NL_ECND_ATTR_LINK_STATE,
	NL_ECND_ATTR_CURRENT_STATE,
	NL_ECND_ATTR_CURRENT_I_KNOW,
	NL_ECND_ATTR_CURRENT_I_SENT,
	NL_ECND_ATTR_ERROR_COUNT,
	NL_ECND_ATTR_ERROR_FLAG,
	NL_ECND_ATTR_ERROR_PFLAG,
	NL_ECND_ATTR_ERROR_STATE,
	NL_ECND_ATTR_ERROR_I_KNOW,
	NL_ECND_ATTR_ERROR_I_SENT,
	NL_ECND_ATTR_ERROR_TIME_SEC,
	NL_ECND_ATTR_ERROR_TIME_NSEC,
	NL_ECND_ATTR_NUM_AIT_MESSAGES,
	NL_ECND_ATTR_TABLE_SIZE,
	NL_ECND_ATTR_TABLE_ID,
	NL_ECND_ATTR_TABLE_LOCATION,
	NL_ECND_ATTR_TABLE_CONTENT,
	NL_ECND_ATTR_TABLE_CONTENT_SIZE,
	NL_ECND_ATTR_AIT_MESSAGE,
	// NL_ECND_ATTR_,

	__NL_ECND_ATTR_AFTER_LAST,
	NL_ECND_ATTR_MAX = __NL_ECND_ATTR_AFTER_LAST - 1
};


/* commands */
enum nl_ecnd_commands {
	NL_ECND_CMD_UNSPEC,

	NL_ECND_CMD_GET_STATE,
	NL_ECND_CMD_ALLOC_TABLE,
	NL_ECND_CMD_FILL_TABLE,
	NL_ECND_CMD_SELECT_TABLE,
	NL_ECND_CMD_DEALLOC_TABLE,
	NL_ECND_CMD_MAP_DRIVERS,
	NL_ECND_CMD_START_FORWARDING,
	NL_ECND_CMD_STOP_FORWARDING,
	NL_ECND_CMD_SEND_AIT_MESSAGE,
	NL_ECND_CMD_RECEIVED_AIT_MESSAGE,

	__NL_ECND_CMD_AFTER_LAST,
	NL_ECND_CMD_MAX = __NL_ECND_CMD_AFTER_LAST - 1
};


#endif
