/*---------------------------------------------------------------------------------------------
 *  Copyright © 2016-present Earth Computing Corporation. All rights reserved.
 *  Licensed under the MIT License. See LICENSE.txt in the project root for license information.
 *  Author: Atsushi Kasuya
 *--------------------------------------------------------------------------------------------*/

#ifndef _ECNL_USER_API_H_
#define _ECNL_USER_API_H_

#define ECNL_GENL_NAME "ECNL_Family"

#define NL_ECNL_MULTICAST_GOUP_LINKSTATUS		"status"
#define NL_ECNL_MULTICAST_GOUP_AIT				"ait"
#define NL_ECNL_MULTICAST_GOUP_ALO				"alo"
#define NL_ECNL_MULTICAST_GOUP_DISCOVERY		"discovery"
#define NL_ECNL_MULTICAST_GOUP_TEST				"test"

/* attributes */
enum nl_ecnd_attributes {
	NL_ECNL_ATTR_UNSPEC,

	NL_ECNL_ATTR_MODULE_NAME,
	NL_ECNL_ATTR_MODULE_ID,
	NL_ECNL_ATTR_NUM_PORTS,

	NL_ECNL_ATTR_PORT_ID,	
	NL_ECNL_ATTR_PORT_NAME,	
	NL_ECNL_ATTR_PORT_LINK_STATE,
	NL_ECNL_ATTR_PORT_S_COUNTER,
	NL_ECNL_ATTR_PORT_R_COUNTER,
	NL_ECNL_ATTR_PORT_RECOVER_COUNTER,
	NL_ECNL_ATTR_PORT_RECOVERED_COUNTER,
	NL_ECNL_ATTR_PORT_ENTT_COUNT,
	NL_ECNL_ATTR_PORT_AOP_COUNT,

	NL_ECNL_ATTR_NUM_AIT_MESSAGES,

	NL_ECNL_ATTR_TABLE_SIZE,
	NL_ECNL_ATTR_TABLE_ID,
	NL_ECNL_ATTR_TABLE_LOCATION,
	NL_ECNL_ATTR_TABLE_CONTENT,
	NL_ECNL_ATTR_TABLE_CONTENT_SIZE,
	NL_ECNL_ATTR_TABLE_ENTRY,
	NL_ECNL_ATTR_TABLE_ENTRY_LOCATION,

	NL_ECNL_ATTR_TABLE_MAP,


	//NL_ECNL_ATTR_DEVICE_U_ADDR,
	//NL_ECNL_ATTR_DEVICE_L_ADDR,

	NL_ECNL_ATTR_MESSAGE,    // AIT and DISCOVER Message, should include header
	NL_ECNL_ATTR_MESSAGE_LENGTH,

	NL_ECNL_ATTR_ALO_REG_VALUES,
	NL_ECNL_ATTR_ALO_FLAG,

	NL_ECNL_ATTR_ALO_REG_DATA,
	NL_ECNL_ATTR_ALO_REG_NO,

	NL_ECNL_ATTR_DISCOVERING_MSG,
	// NL_ECNL_ATTR_,

	__NL_ECNL_ATTR_AFTER_LAST,
	NL_ECNL_ATTR_MAX = __NL_ECNL_ATTR_AFTER_LAST - 1
};


/* commands */
enum nl_ecnd_commands {
	NL_ECNL_CMD_UNSPEC,

	NL_ECNL_CMD_ALLOC_DRIVER,

	NL_ECNL_CMD_GET_MODULE_INFO,

	NL_ECNL_CMD_GET_PORT_STATE,

	NL_ECNL_CMD_ALLOC_TABLE,
	NL_ECNL_CMD_FILL_TABLE,
	NL_ECNL_CMD_FILL_TABLE_ENTRY,
	NL_ECNL_CMD_SELECT_TABLE,
	NL_ECNL_CMD_DEALLOC_TABLE,
	
	NL_ECNL_CMD_MAP_PORTS,

	NL_ECNL_CMD_START_FORWARDING,
	NL_ECNL_CMD_STOP_FORWARDING,

	NL_ECNL_CMD_SEND_AIT_MESSAGE,
	NL_ECNL_CMD_SIGNAL_AIT_MESSAGE,
	NL_ECNL_CMD_RETRIEVE_AIT_MESSAGE,

	NL_ECNL_CMD_WRITE_ALO_REGISTER,
	NL_ECNL_CMD_READ_ALO_REGISTERS,

	NL_ECNL_CMD_SEND_DISCOVER_MESSAGE,

	__NL_ECNL_CMD_AFTER_LAST,
	NL_ECNL_CMD_MAX = __NL_ECNL_CMD_AFTER_LAST - 1
};


#define ENCL_FW_TABLE_ENTRY_ARRAY	15
typedef struct ecnl_table_entry 
{
	union {
		struct {
			unsigned int reserved : 12 ;
			unsigned int parent : 4 ;
			unsigned int port_vector : 16 ;
		} ;
		uint32_t raw_vector ;
	} info ;
	uint32_t nextID[ENCL_FW_TABLE_ENTRY_ARRAY] ;
} ecnl_table_entry_t ;


#endif
