/* 
 * Earth Computing Network Link Device User API
 * Copyright(c) 2016 Earth Computing.
 *
 *  Author: Atsushi Kasuya
 *
 */

#ifndef _ENTL_DUMMY_USER_API_H_
#define _ENTL_DUMMY_USER_API_H_

#define ECTLD_GENL_NAME "ENTL_Dummy_Family"

#define NL_ECTLD_MULTICAST_GOUP_LINKSTATUS		"status"
#define NL_ECTLD_MULTICAST_GOUP_DISCOVERY		"discovery"
#define NL_ECTLD_MULTICAST_GOUP_TEST			"test"

/* attributes */
enum nl_entld_attributes {
	NL_ENTLD_ATTR_UNSPEC,

	NL_ENTLD_ATTR_PARENT_NAME,
	NL_ENTLD_ATTR_PORT_NAME,	
	NL_ENTLD_ATTR_PORT_ID,	
	NL_ENTLD_ATTR_LINK_STATE,

	NL_ENTLD_ATTR_LINK_PEER_0,
	NL_ENTLD_ATTR_LINK_PEER_1,

	NL_ENTLD_ATTR_DEVICE_U_ADDR,
	NL_ENTLD_ATTR_DEVICE_L_ADDR,

	NL_ENTLD_ATTR_AIT_MESSAGE,

	NL_ENTLD_ATTR_DISCOVERING_MSG,

	NL_ENTLD_ATTR_MSG_LENGTH,

	// NL_ENTLD_ATTR_,

	__NL_ENTLD_ATTR_AFTER_LAST,
	NL_ENTLD_ATTR_MAX = __NL_ENTLD_ATTR_AFTER_LAST - 1
};


/* commands */
enum nl_entld_commands {
	NL_ENTLD_CMD_UNSPEC,

	NL_ENTLD_CMD_ALLOC_DRIVER,

	NL_ENTLD_CMD_GET_STATE,
	NL_ENTLD_CMD_CONNECT_PEER,

	NL_ENTLD_CMD_SEND_DISCOVER_MESSAGE,

	__NL_ENTLD_CMD_AFTER_LAST,
	NL_ENTLD_CMD_MAX = __NL_ENTLD_CMD_AFTER_LAST - 1
};

#endif
