
CFLAGS += -I/usr/include/libnl3
LDLIBS += -lnl-genl-3 -lnl-3
CFLAGS += -I/home/demouser/earthcomputing/bj-NALDD/entl_drivers/ecnl_device

all: genl_sample

# sudo insmod ecnl_device.ko
# sudo env NLCB=debug ./genl_sample
